hw1
nvsich/java-backend-tinkoff-course pull request #1
Opened 2024-02-18 19:09 UTC by nvsich

Телеграм бот с рабочим меню. Можно добавлять и удалять ссылки (в памяти, без БД).

2024-02-20 21:36 UTC, x1vr64 requested changes
- Стоит подумать над иерархией классов. Не понятен выбор выделенных методов в интерфейсах (Например зачем выделять метод execute + Не нужно передавать зависимости сервиса через параметры метода интерфейса)
 - Не хватает обертки над использованием библиотеки. Сейчас классы библиотеки находятся везде. При ее замене/изменнении, придется много переделывать
 - Странные сообщения в чате (Например, если сначала ввести /track, а потом ввести /help, то бот напишет что надо ввести /help, чтобы узнать про команды)
 - Дополнительное задание лучше делать как указано в задании( Сейчас они реализованы через кнопки в приложении, что не позволяет телеграму делать автокомплит команд с клавиатуры
 - Тесты походу сгенеренные, они просто проверяют захардкоженные текстовки. В них лучше бы проверить, как работают особые случаи (Например вывод сообщения, при нескольких значениях, чем захардкоженные строчки)
 - Странное использование applicationContext. Используется для получения всех команд, при этом в коде есть также использование List<Command>. Рекомендуется везде использовать List<Command>

2024-02-20 21:36 UTC, x1vr64 commented on bot/pom.xml
> +        </dependency>
Бд нет, но зависимости остались) 

P.S. H2 это бд

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/bot/Bot.java
> +    <T extends BaseRequest<T, R>, R extends BaseResponse> void execute(BaseRequest<T, R> request);
Не понимаю, зачем этот метод в интерфейсе. По сути это мог бы быть приватный метод реализации.

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/command/Command.java
> +    }
Метод нигде не используется. Надо стараться не оставлять мертвый код

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/bot/BotImpl.java
> +    }
В некоторых местах проекта есть использование аннотации AllArgsConstructor, при этом тут ты делаешь это вручную. Надо придерживаться одного подхода.

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +        @Value("${app.telegram-token}") String telegramToken,
Тут нужно было использовать класс ApplicationConfig.

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/command/HelpCommand.java
> +        var beans = applicationContext.getBeansOfType(Command.class);
Наше сообщение будет строиться каждый раз, когда мы вызываем команду /help, хотя она и не меняется. Надо бы это один раз сделать сообщение и отдовать пользователю при вызове команды.

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/processor/ChatStateAction.java
> +    boolean execute(ChatStateRepo chatStateRepo, LinkRepo linkRepo, Long chatId, String link);
Передавать зависимости через параметры метода в интерфейсе звучит дико. При добавлении новых фич данный код придется переписывать

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/processor/StopTrackingLink.java
> +        }
С отслеживанием ссылки можно упасть с ошибкой, а здесь я не вижу причин для try catch

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/processor/StopTrackingLink.java
> +        chatStateRepo.setChatStateByChatId(chatId, ChatState.WAITING_FOR_COMMAND);
Получается оба ChatStateAction сначала изменяют состояние на ожидание команды. Надо бы вынести это в другое место, чтобы класс делал тлоько одно дело

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/processor/StartTrackingLink.java
> +        }
Ошибки нужно логировать, иначе мы будем думать чт оу нас все хорошо, хотя на самом деле у нас проблемы

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +        this.keyboard = new CommandsKeyboard(applicationContext);
Мы в параметрах передали список комманд. Его можно использовать и в CommandsKeyboard, вместо снова applicationContext

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/utility/CommandsKeyboard.java
> +        return new ReplyKeyboardMarkup(buttonsArray).resizeKeyboard(true);
Можно посмотреть на streamApi для работы с коллекциями. Также стоит как и в случае команды /help сделать это один раз и сохранить в поле, чтобы каждый раз не использовать applicationContext

2024-02-20 21:36 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/utility/LinkParser.java
> +        return response.getStatusCode().is2xxSuccessful();
Идея хорошая, но лучше так не делать) Если ты запустишь бота на своем компьютере, люди могут через твой компьютер делать плохие вещи) (Ну или взломать тебя, на крайний случай)

2024-02-25 10:44 UTC, nvsich commented
Здравствуйте!
Спасибо за отзыв. Переделал работу, сильно изменил архитектуру.

Основные изменения:

- Вынес работу с телеграм библиотекой в отдельный класс (сделал обертку)
- Добавил проверку на источник ссылки в виде цепочки обязанностей (Github, StackOverflow)
- Добавил unit тесты
- Всю основную бизнес-логику вынес в handle методы комманд.

2024-02-29 18:04 UTC, x1vr64 approved these changes
Отличная работа) Минорные правки толька

2024-02-29 18:04 UTC, x1vr64 commented on .github/workflows/bot.yml
> +      - .github/workflows/telegrambot.yml
Файл .github/workflows/bot.yml сломался( Тесты должны прогоняться, иначе смысла в них нет

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/entity/factory/impl/LinkFactoryImpl.java
> +
В целом заносить библиотеку commons для одной проверки выглядит расходно, но ладно. Можно было использовать стандартную библиотку java (Например класс URL)

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/entity/enums/LinkDomain.java
> +            Matcher matcher = pattern.matcher(url);
Класс Pattern можно создать 1 раз и переиспользовать. Просто он каждый раз будет парсить твое regex выражение, но оно не меняется от разу к разу

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/entity/enums/LinkDomain.java
> +            Matcher matcher = pattern.matcher(url);
Название enum лучше делать как у констант. Например как сделал ниже (NOT_SUPPORTED)

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/entity/factory/impl/LinkFactoryImpl.java
> +            new URI(fullUrl).toURL().openStream().close();
В целом делать проверку на старте, что мы можем сделать запрос до ресурса может и имеет смысл, но тогда работа нашего бота завязывается на работоспособность соединения от бека до сайта.

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/main/java/edu/java/bot/service/command/HelpCommand.java
> +    @Transactional
В домашке, где будем прикручивать БД, мы со всеми Transactional разберемся

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/test/java/edu/java/bot/service/command/HelpCommandTest.java
> +        assertEquals(chatId, actualResponse.getChatId());
Добавить бы еще само форматирование. Но это уже отлично

2024-02-29 18:04 UTC, x1vr64 commented on bot/src/test/java/edu/java/bot/service/command/HelpCommandTest.java
> +        MessageRequest mockRequest = mock(MessageRequest.class);
Т.е. это условно модель с данными без логики, лучше бы использовать сразу MessageRequest. После потом из этого целые testFixtures начинают выделяться, образуя тестовую модель

2024-02-29 19:53 UTC, merged