hw3: tasks 1, 2, 3, 4
nvsich/java-backend-tinkoff-course pull request #3
Opened 2024-03-02 20:47 UTC by nvsich

2024-03-02 20:54 UTC, nvsich commented
Пока что сделал заглушки вместо реализации методов контроллеров в scrapper. 
Немного не понимаю какая сейчас должна быть структура: в задании говорилось, что мы отправляем запросы из модуля bot в scrapper на добавление/удаление чатов, добавление/удаление ссылок и тд. То есть в модуле bot у нас вообще не должно быть хранения никаких данных? 
Сейчас в моей реализации все данные хранятся в модуле bot, я правильно понимаю, что нужно переделать проект так, чтобы путь данных был такой: user -> telegram api -> commands handle -> request to scrapper client -> scrapper's controllers handling request -> database in scrapper -> scrapper client returns response in bot -> handling response (correct/exception) in bot -> send message to user?

2024-03-08 19:50 UTC, nvsich commented
Переделал архитектуру. Перенес всю работу с данными в модуль scrapper. В модуле bot осталось только хранение состояния чата. Убрал заглушки из модуля scrapper, сделал реализацию репозиториев, сервисов и тд и тп.

2024-03-13 06:36 UTC, SHvatov requested changes
@nvsich оставил пару комментариев, посмотри их, пожалуйста. С учетом задержек, предлагаю  поступить следующим образом - за домашку я оценку поставлю, а ты в оффлйне поправишь мои комменты.

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/api/client/ScrapperClient.java
> +public interface ScrapperClient {
Вроде бы пересылал тебе свое сообщений в группе в телеге по поводу интерфейсов. Они хороши, но когда имеют смысл. Предполагаются ли какие-либо другие реализации данного интерфейса?

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/api/client/ScrapperClient.java
> +    Mono<LinkResponse> deleteLinkForChat(Long tgChatId, RemoveLinkRequest removeLinkRequest);
Чуть-чуть подушню, но раз метод `delete...`, то и `RemoveLinkRequest` я бы заменил на `DeleteLinkRequest`)

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/api/client/impl/ScrapperClientImpl.java
> +    public Mono<Void> registerChat(Long id) {
Советую использовать либо `HTTP Interface`, либо `RestClient`. На крайняк - `WebClient`, но наружу отдавать не `Mono`. Реактивщина шутка очень специфичная, сейчас я над ней запариваться не советую, да и она не имеет почти никакого смысла / профита в нереактивных проектах.

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/entity/ChatState.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Лучше SEQUENCE с названием сиквенса. https://stackoverflow.com/questions/17780394/hibernate-identity-vs-sequence-entity-identifier-generators.

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/exception/LinkNotFoundException.java
> +public class LinkNotFoundException extends RuntimeException {
С одной стороны хорошо, что на каждый кейс есть свое исключение и их можно дифференцировать, но я в последнее время пришел к мнению, что для АПИ лучше иметь   одно исключение, в котором будет все, что нужно - внутреннее сообщение для разрабов, сообщение для пользака, статус ответа. Подумай, может в твоем случае такой вариант тоже зайдет?

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/ListCommand.java
> +            var listLinkResponseFromClient = scrapperClient.getAllLinksForChat(chatId).block();
Смотри, сейчас у тебя try/cacth на достаточно большой объем логики, и тут два момента
1. Будет расти блок catch'ей при необходимости обработки новых исключений
2. Могут возникнуть коллизии - одно исключение, в двух разных сервисах, при этом их нужно по разному обработать. 

Поэтому:
1. Старайся делать так - один catch, один стейтмент (если это конечно не работа сресурсами)
2. Давай тут на методы разобьем - получение линков и их обработка?

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/ListCommand.java
> +            var listLinkResponseFromClient = scrapperClient.getAllLinksForChat(chatId).block();
`listLinkResponseFromClient` - а ответ может быть не от клиента?) название слишком вербозное (`aListOfLinkWeGotFromScrapperServiceAsAResponseToOurRequest`)))

2024-03-13 06:36 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/StartCommand.java
> +                scrapperClient.registerChat(chatId).block();
А если не удастся зарегистрировать чат?

2024-03-13 06:36 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/processor/impl/LinksProcessorImpl.java
> +        Link link;
1. Мне не очень нравятся разделение объявления и определения переменной
2. Почему бы фабрике не обрабатывать эти исключения? Вроде как именно она ответственна за создание корректной ссылки.

2024-03-15 10:25 UTC, nvsich commented on bot/src/main/java/edu/java/bot/api/client/ScrapperClient.java
> +public interface ScrapperClient {
Сообщение видел, просто по привычке сделал интерфейс)

2024-03-15 21:45 UTC, nvsich commented on bot/src/main/java/edu/java/bot/exception/LinkNotFoundException.java
> +public class LinkNotFoundException extends RuntimeException {
Думал так сделать, но у меня эти исключения не только для АПИ, некоторые используются и просто в приложении (в частности ChatNotFoundException, который я прокидываю из команд, если чат не найден и обрабатываю в LinkUpdateProcessor, и одновременно прокидываю из клиента скраппера). В общем, если сделать общий тип исключений для АПИ, то все равно останутся исключения для приложения, и тогда уже как будто потеряется изначальный смысл в объединении исключений, если их все равно будет несколько

2024-03-15 23:17 UTC, merged